# Generated by Django 5.0.6 on 2024-10-20 05:35

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "start_time",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "logs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("success", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-start_time",),
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("map", models.CharField(max_length=255)),
                ("replay_url", models.URLField(max_length=500)),
                ("game_version", models.CharField(max_length=10)),
                ("starting_cash", models.IntegerField()),
                ("match_length", models.DurationField()),
                ("match_type", models.CharField(max_length=20)),
                ("match_timestamp", models.DateTimeField()),
                ("replay_size", models.IntegerField(help_text="Size of the replay file in KB")),
                ("replay_upload_timestamp", models.DateTimeField(null=True)),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="zh.jobrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "matches",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("player_name", models.CharField(db_index=True, max_length=100)),
                (
                    "gentool_id",
                    models.CharField(blank=True, db_index=True, max_length=32, null=True),
                ),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="zh.jobrun",
                    ),
                ),
            ],
            options={
                "ordering": ("player_name",),
            },
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("team", models.IntegerField(blank=True, null=True)),
                ("army", models.CharField(max_length=25)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="zh.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="zh.player",
                    ),
                ),
            ],
            options={
                "ordering": ("team",),
            },
        ),
        migrations.AddField(
            model_name="match",
            name="replay_uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_matches",
                to="zh.player",
            ),
        ),
    ]
