JAZZMIN_SETTINGS = {
    "site_title": "Zero Hour Stats",
    "site_header": "Zero Hour Stats",
    "site_brand": "Zero Hour Stats",
    "site_logo_classes": "img-circle",
    "topmenu_links": [],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "show_ui_builder": True,
    "site_logo": "zh/img/logo.jpg",
    "login_logo": "zh/img/logo.jpg",
    "login_logo_dark": None,
    "site_icon": None,
    "search_model": [],
    "user_avatar": None,
    "usermenu_links": [],
    "hide_apps": [],
    "order_with_respect_to": [],
    "custom_links": {},
    "custom_css": "zh/css/style.css",
    "custom_js": None,
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-success",
    "accent": "accent-lime",
    "navbar": "navbar-secondary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-lime",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

# This is needed for modals to work since they work like iframes
X_FRAME_OPTIONS = "SAMEORIGIN"
